arch:
  - amd64
  - ppc64le

language: python

dist: xenial
os: linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "3.10-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
- pip install pytest
- pip install pycodestyle

script:
- py.test
- make test_codestyle
- make testwarnings
